name: Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure this matches your local environment

    - name: Install Dependencies
      working-directory: ./backend
      run: |
        npm install --verbose  # This provides detailed output

    - name: Zip Backend Folder
      run: |
        cd backend
        zip -r ../backend.zip . || echo "Zipping failed"  # Capture zipping issues

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: mox-backend  # Replace with your Azure App name
        package: backend.zip
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
